#!/usr/bin/env python3
"""Pocket RPG font converter: TTF -> anti-aliased 4-bit glyphs for the board (firmware/PocketRPG/fonts.h).

Usage:  python3 tools/build_fonts.py      (needs: pip install pillow)
Fonts come from tools/fonts/ (Silkscreen for titles, Atkinson Hyperlegible for everything else).
Each glyph keeps 16 levels of coverage, so text is smooth on the AMOLED.
"""
import os
from PIL import ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "firmware", "PocketRPG", "fonts.h")
SILK = os.path.join(HERE, "fonts", "Silkscreen-Regular.ttf")
BOLD = os.path.join(HERE, "fonts", "AtkinsonHyperlegible-Bold.ttf")
REG = os.path.join(HERE, "fonts", "AtkinsonHyperlegible-Regular.ttf")

SILKB = os.path.join(HERE, "fonts", "Silkscreen-Bold.ttf")
# The whole game uses Silkscreen, a pixel font: drawn at its native 8 px and blown up by whole pixels
# (x2 = 16 px, x3 = 24 px, ...), so every letter stays crisp.
# The "B" fonts are a semi-bold: the regular letters thickened sideways by a third of a font pixel (at
# least 1 screen pixel). Silkscreen's own Bold doubles every stroke and is hard to read on the small screen.
FONTS = [
    ("PX16", SILK, 2), ("PX24", SILK, 3), ("PX32", SILK, 4),
    ("PXB16", SILK, 2, "semi"), ("PXB24", SILK, 3, "semi"), ("PXB48", SILK, 6, "semi"),
]
# printable ASCII, then the two extra characters the UI uses (middle dot, ellipsis)
CHARS = [chr(c) for c in range(32, 127)] + ["·", "…"]


def build(name, path, size, style=None):
    scale = 1
    if path in (SILK, SILKB):
        scale, size = size, 8
    f = ImageFont.truetype(path, size)
    asc, desc = f.getmetrics()
    asc, desc = asc * scale, desc * scale
    glyphs, data = [], bytearray()
    for ch in CHARS:
        adv = int(round(f.getlength(ch))) * scale
        try:
            mask, (ox, oy) = f.getmask2(ch, mode="L", anchor="ls")
        except Exception:
            mask, (ox, oy) = None, (0, 0)
        w, h = (mask.size if mask is not None else (0, 0))
        if ch == " " or w == 0 or h == 0:
            glyphs.append((len(data), 0, 0, 0, 0, adv))
            continue
        px = bytes(mask)
        if scale > 1:  # crisp: threshold, then repeat every pixel scale x scale
            px = bytes(255 if v >= 128 else 0 for v in px)
            extra = max(1, scale // 3) if style == "semi" else 0
            big = bytearray()
            for y in range(h):
                row = bytearray()
                for x in range(w):
                    row += bytes([px[y * w + x]]) * scale
                row += bytes(extra)
                if extra:   # thicken: each lit pixel also lights the next `extra` pixels to its right
                    src = bytes(row)
                    for x in range(len(row)):
                        if any(src[x - k] for k in range(1, extra + 1) if x - k >= 0):
                            row[x] = 255
                big += bytes(row) * scale
            px, w, h, ox, oy = bytes(big), w * scale + extra, h * scale, ox * scale, oy * scale
            adv += extra
        # trim empty columns/rows
        rows = [px[y * w:(y + 1) * w] for y in range(h)]
        top = next((y for y in range(h) if any(rows[y])), 0)
        bot = next((y for y in range(h - 1, -1, -1) if any(rows[y])), h - 1)
        left = min((next((x for x in range(w) if r[x]), w) for r in rows[top:bot + 1]), default=0)
        right = max((next((x for x in range(w - 1, -1, -1) if r[x]), -1) for r in rows[top:bot + 1]), default=-1)
        if right < left:
            glyphs.append((len(data), 0, 0, 0, 0, adv))
            continue
        gw, gh = right - left + 1, bot - top + 1
        off = len(data)
        nib = []
        for y in range(top, bot + 1):
            for x in range(left, right + 1):
                nib.append((rows[y][x] * 15 + 127) // 255)
        if len(nib) % 2:
            nib.append(0)
        for i in range(0, len(nib), 2):
            data.append((nib[i] << 4) | nib[i + 1])
        glyphs.append((off, gw, gh, ox + left, oy + top, adv))
    lines = [f"static const uint8_t {name}_BITS[{max(1, len(data))}] = {{"]
    for i in range(0, len(data), 32):
        lines.append("  " + ",".join(str(b) for b in data[i:i + 32]) + ",")
    if not data:
        lines.append("  0,")
    lines.append("};")
    lines.append(f"static const Glyph {name}_GLYPHS[{len(glyphs)}] = {{")
    for g in glyphs:
        lines.append("  {%d,%d,%d,%d,%d,%d}," % g)
    lines.append("};")
    lines.append(f"const Font FONT_{name} = {{ {name}_BITS, {name}_GLYPHS, {asc}, {desc} }};")
    return "\n".join(lines), len(data)


def main():
    parts, total = [], 0
    for name, path, size, *style in FONTS:
        s, n = build(name, path, size, style[0] if style else None)
        parts.append(s)
        total += n
    with open(OUT, "w") as fh:
        fh.write("// Generated by tools/build_fonts.py. Do not edit by hand.\n#pragma once\n#include \"ui_gfx.h\"\n\n")
        fh.write("\n\n".join(parts) + "\n")
    print(f"wrote {OUT}: {len(FONTS)} fonts, {total / 1024:.0f} KB of glyphs")


if __name__ == "__main__":
    main()
